### ISSUE TITLE
The form does not work on files imported from .stp

### ISSUE THREAD

**Issue by Erikowaty** [koechlm/VDS-Sample-Configuration-2023#8]
Hello,
I have a problem with files imported from .stp.
After translation, the VDS form under inventor does not work.

**Comment by koechlm** [comment]
Hello @Erikowaty, this behavior is an intended behavior of this sample configuration. We recommend not handling file by file for imported data in VDS rather than using the mass edit capabilities of either Inventor Vault Data Cards or Vault Property Table Editing. If you want to enable it, just remove the "Sending System" from CAD.Custom\Configuration\Inventor.cfg: https://github.com/koechlm/VDS-Sample-Configuration-2023/blob/master/VDS-2023-MFG-Sample/CAD.Custom/Configuration/Inventor.cfg. Also note that the Inventor Tutorial, chapter 05 describes this behavior and setup in more detail.

**Comment by Erikowaty** [comment]
Hello,
Thank you for the quick reply,

After removing "Sending System", I get an error in the Inventor.xaml file. Do I need to make any additional settings here?

![2023-07-12 174714](https://github.com/koechlm/VDS-Sample-Configuration-2023/assets/60139213/afa3830e-24b4-443d-be64-28c295f4f573)

**Comment by koechlm** [comment]
Hello, this error is unrelated to our previous topic; it relates to the theme's support of Vault 2023.2 and higher. The sample configuration requires the minimum update 2023.2 installed, respectively.

**Comment by Erikowaty** [comment]
Yes, update 2023.3.1 fixed the issue.
Thank you
